eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
 
management:
  tracing:
    sampling:
      probability: 1.0
 
 okta:
  oauth2:
    issuer: https://dev-91874823.okta.com/oauth2/default
    audience: api://default
     
